# Generated by Django 4.0.4 on 2024-01-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_name', models.TextField(null=True)),
                ('dates', models.TextField(null=True)),
                ('price_open', models.TextField(null=True)),
                ('price_high', models.TextField(null=True)),
                ('price_low', models.TextField(null=True)),
                ('price_close', models.TextField(null=True)),
                ('volume', models.TextField(null=True)),
                ('average_open', models.FloatField()),
                ('average_close', models.FloatField()),
                ('min_open', models.FloatField()),
                ('max_close', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_visitor_name', models.CharField(max_length=200)),
            ],
        ),
    ]
